const usersData = [
    {
        firstName: 'Sybille',
        lastName: 'Vignal',
        password: 'Boubourette11@',
        points: 185,
        dateOfBirth: '13 décembre 2011 à 8h00',
        notes: 'Elle partage presque les mêmes centres d’intérêt, et elle est gentille et marrante.',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: '13 Rue de la République a Magenta (51530)',
        phoneNumber: '07 44 71 72 18'
    },
    {
        firstName: 'Gianni',
        lastName: 'Blaz',
        password: process.env.ADMIN_PASS,
        points: 0,
        dateOfBirth: 'Censure',
        notes: 'Administrateur du site.',
        loveLife: 'Censure',
        numberOfCrosses: 0,
        address: 'Censure',
        phoneNumber: 'Censure'
    },
    {
        firstName: 'Gabin',
        lastName: 'Lefevre',
        password: 'PuLsViTe55',
        points: 75,
        dateOfBirth: '04 avril 2012',
        notes: 'Pas tres dispo !',
        loveLife: 'Célibataire',
        numberOfCrosses: 1,
        address: 'Inconnue',
        phoneNumber: '06 52 04 87 18'
    },
    {
        firstName: 'Victory-Anna',
        lastName: 'Da Costa',
        password: 'G14nn1LEGOAT',
        points: 100,
        dateOfBirth: '4 mars 2012',
        notes: '👉 Gentille, marrante et un peu folle.',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: '07 66 60 24 60'
    },
    {
        firstName: 'Joël',
        lastName: 'Lagadec',
        password: 'XXX2025/2026',
        points: 77,
        dateOfBirth: '10 avril 2012',
        notes: '💻 Fan d’informatique',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: '07 75 74 14 36'
    },
    {
        firstName: 'Louise',
        lastName: 'Lebadi',
        password: 'Giannietlouise',
        points: 175,
        dateOfBirth: '13 mars 2012',
        notes: '🌞 Fan des colos',
        loveLife: 'En couple',
        numberOfCrosses: 0,
        address: '148 avenue Gabriel Péri. (94 170) Le Perreux',
        phoneNumber: '07 49 52 38 30'
    },
    {
        firstName: 'Taylor',
        lastName: 'Dejussel',
        password: 'Grizouthegoats',
        points: 122,
        dateOfBirth: '5 juillet 2012',
        notes: '👉 Aime le foot et les jeux vidéo',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: '07 49 52 38 30'
    },
    {
        firstName: 'Leda',
        lastName: 'Tiste',
        password: '!ticket',
        points: 92,
        dateOfBirth: '7 juillet 2010',
        notes: '🎮 Brawlhalla addict',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: 'Inconnue'
    },
    {
        firstName: 'Denisa',
        lastName: 'Gherasim',
        password: 'Denisa142012_94.',
        points: 53,
        dateOfBirth: '14 mars 2012',
        notes: '🤐 Parle pas trop',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: '07 83 76 64 01'
    },
    {
        firstName: 'Ethan',
        lastName: 'Beranger',
        password: 'FireBird30&',
        points: 135,
        dateOfBirth: '4 février 2011',
        notes: 'JSP',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: 'Inconnue'
    },
    {
        firstName: 'Marilou',
        lastName: 'Longuèvre',
        password: '1234',
        points: 75,
        dateOfBirth: '19 Aout 2009',
        notes: '🎪 Stalkeuse, fan de cirque, apparemment BE',
        loveLife: 'En couple',
        numberOfCrosses: 0,
        address: '10 petite rue Ligny le chatel',
        phoneNumber: '06 18 42 52 80'
    },
    {
        firstName: 'Hugo',
        lastName: 'Hejelouis',
        password: 'Pell!883::%9,_*',
        points: 0,
        dateOfBirth: '3 septembre 2012',
        notes: '👑 Technoblade | Fan de Minecraft & RP',
        loveLife: 'Célibataire',
        numberOfCrosses: 1,
        address: 'Inconnue',
        phoneNumber: 'Inconnue'
    },
    {
        firstName: 'Simon',
        lastName: 'Monnet',
        password: 'simsim36785_',
        points: 75,
        dateOfBirth: '24 décembre 2011',
        notes: '🎥 Potentiel futur YouTubeur, et très gentil',
        loveLife: 'Célibataire',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: 'Inconnue'
    },
    {
        firstName: 'Mahiti',
        lastName: 'Payet',
        password: 'Error404',
        points: 55,
        dateOfBirth: '21 août 2015',
        notes: '🎮 Ami récent | Officiel | Connu sur Fortnite ⚠️ (risque de suppression)',
        loveLife: 'JSP',
        numberOfCrosses: 0,
        address: 'Inconnue',
        phoneNumber: 'Inconnue'
    },
];
